server:
  port: 8087
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gerenciamentodb
    username: gerenciamento_user
    password: gerenciamento_pass
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  sql:
    init:
      mode: always