server:
  port: 8087
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gerenciamentodb
    username: gerenciamento_user
    password: gerenciamento_pass
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: localhost:9092
    topic: pedidotopic
    topic-dlq: pedidotopic-dlq
    consumer:
      group-id: grupo-pedidotopic-receiver
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer